### ISSUE TITLE
请问楼主，data中的数据/data/hlm/hlm.txt在哪呢，是需要爬吗 还是怎样

### ISSUE THREAD

**Issue by liuhy0908** [lipiji/rnn-theano#2]

**Comment by lipiji** [comment]
去找一个下载就行，红楼梦txt，版权问题我就不传播了。

**Comment by liuhy0908** [comment]
多谢楼主！已经下载了红楼梦，可是程序还是报错
IOError: [Errno 2] No such file or directory: './data/hlm/name.dic'
这个name.dic又是什么呢

**Comment by liuhy0908** [comment]
楼主可否把完整的数据发给我呢，一直在找相关的项目，却总是报错，拜托楼主棒棒忙，楼主如果不方便可以直接发到我的邮箱：liuhongyue88@126.com，拜托了楼主！！！

**Comment by liuhy0908** [comment]
报错：compiling...
Traceback (most recent call last):
  File "main_hlm_train.py", line 29, in <module>
    model = RNN(dim_x, dim_y, hidden_size, cell, optimizer, drop_rate)
  File "/home/tagtic/liuhy/hlm_rnn/rnn.py", line 26, in **init**
    self.define_layers()
  File "/home/tagtic/liuhy/hlm_rnn/rnn.py", line 44, in define_layers
    self.maskX, self.is_train, self.batch_size, self.drop_rate)
  File "/home/tagtic/liuhy/hlm_rnn/gru.py", line 42, in **init**
    outputs_info = [T.alloc(floatX(0.), 1, batch_size \* self.out_size)])
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 1042, in scan
    scan_outs = local_op(_scan_inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 507, in **call**
    node = self.make_node(_inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 357, in make_node
    outer_sitsot = format(_outer_sitsot, as_var=inner_sitsot)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 258, in format
    rval = tmp.filter_variable(rval)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 218, in filter_variable
    self=self)
TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable IncSubtensor{Set;:int64:}.0) into Type TensorType(float32, (False, True, False)). You can try to manually convert IncSubtensor{Set;:int64:}.0 into a TensorType(float32, (False, True, False)).
